from pydantic import BaseModel, EmailStr, Field
from typing import Optional, Literal
import uuid


class UserLogin(BaseModel):
    email: EmailStr
    # Cap length so an attacker can't send a multi-MB password and pin the CPU
    # on bcrypt (deliberately slow). bcrypt only uses the first 72 bytes anyway.
    # min_length=1 here (not 8) so we never lock out an existing account.
    password: str = Field(min_length=1, max_length=128)


class UserRegister(BaseModel):
    email: EmailStr
    password: str = Field(min_length=8, max_length=128)
    role: Literal["admin", "faculty", "student"]
    full_name: str = Field(min_length=1, max_length=100)

    # Optional — auto-generated by the server if not supplied.
    enrollment_no: Optional[str] = Field(default=None, max_length=20)
    employee_id: Optional[str] = Field(default=None, max_length=20)


class TokenResponse(BaseModel):
    role: str


class UserMeResponse(BaseModel):
    id: uuid.UUID
    email: str
    role: str