from pydantic import BaseModel, EmailStr
from typing import Optional, Literal
import uuid

# What is expected from the frontend when logging in
class UserLogin(BaseModel):
    email: EmailStr
    password: str

# Used by the admin-only "create user" endpoint — there is no public
# self-registration route. enrollment_no / employee_id are optional:
# if omitted, the backend auto-generates one (e.g. STU00001, FAC00001).
class UserRegister(BaseModel):
    email: EmailStr
    password: str
    role: Literal["admin", "faculty", "student"]
    full_name: str

    # Optional — auto-generated by the server if not supplied
    enrollment_no: Optional[str] = None
    employee_id: Optional[str] = None

# The token is no longer returned in the body — it's set as an httpOnly cookie.
# We only return the role so the frontend knows where to redirect.
class TokenResponse(BaseModel):
    role: str

class UserMeResponse(BaseModel):
    # pydantic validates/serializes uuid.UUID automatically to a string in JSON
    id: uuid.UUID
    email: str
    role: str