"""edited models for materials to work with s3 bucket

Revision ID: 905d92fa9d46
Revises: 770eb4d70028
Create Date: 2026-07-05 22:35:02.174606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '905d92fa9d46'
down_revision: Union[str, Sequence[str], None] = '770eb4d70028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_materials', sa.Column('object_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_materials', 'object_key')
    # ### end Alembic commands ###
