"""add object key to submission for students

Revision ID: b45737e31252
Revises: fadbbf5a5506
Create Date: 2026-07-06 18:27:59.709413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45737e31252'
down_revision: Union[str, Sequence[str], None] = 'fadbbf5a5506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('object_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'object_key')
    # ### end Alembic commands ###
