"""updated atendence table

Revision ID: c49534c29234
Revises: b45737e31252
Create Date: 2026-07-07 19:04:17.128136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c49534c29234'
down_revision: Union[str, Sequence[str], None] = 'b45737e31252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('class_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_attendance_student_class_date', 'attendance', ['student_id', 'class_id', 'date'])
    op.create_foreign_key(None, 'attendance', 'class_groups', ['class_id'], ['id'], ondelete='CASCADE')
    op.drop_column('attendance', 'subject')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'attendance', type_='foreignkey')
    op.drop_constraint('uq_attendance_student_class_date', 'attendance', type_='unique')
    op.drop_column('attendance', 'class_id')
    # ### end Alembic commands ###
