"""added code column to ClassGroup table

Revision ID: cb3d554449a1
Revises: 59bf80382cfe
Create Date: 2026-07-04 16:31:51.281131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb3d554449a1'
down_revision: Union[str, Sequence[str], None] = '59bf80382cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_groups', sa.Column('code', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'class_groups', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'class_groups', type_='unique')
    op.drop_column('class_groups', 'code')
    # ### end Alembic commands ###
