"""added upload link for faculty material upload option

Revision ID: fadbbf5a5506
Revises: 28d9e5388982
Create Date: 2026-07-06 18:05:13.204416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fadbbf5a5506'
down_revision: Union[str, Sequence[str], None] = '28d9e5388982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_materials', sa.Column('source_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_materials', 'source_type')
    # ### end Alembic commands ###
